### ISSUE TITLE
Version 1.0.0 Requirements

### ISSUE THREAD

**Issue by bigtimebuddy** [jiborobot/pixi-animate#28]
## Todo List

* [x] Convert build process to **pixify**
* [x] Remove **loophole** from `dependencies`
* [x] Move **pixi.js** to `peerDependencies` make a property plugin
* [x] Add Typescript typings

**Comment by bigtimebuddy** [comment]
See #29
